# Generated by Django 3.0 on 2019-12-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Header', max_length=64)),
                ('text', models.TextField(default='Veniam eiusmod irure est aliqua aliqua aliqua minim ut sit incididunt enim sit exercitation proident.')),
            ],
        ),
    ]
